export default {
  tp:       'color:transparent!important',
  thin:     'font-weight:lighter',
  normal:   'font-weight:normal',
  bold:     'font-weight:bold',
  bolder:   'font-weight:bolder',
  italic:   'font-style: italic',
  delete:   'text-decoration-line:line-through',
  line:     'text-decoration-line:underline',
  overline: 'text-decoration-line:overline',
  up:       'text-transform:uppercase',
  low:      'text-transform:lowercase',
  cap:      'text-transform:capitalize',
  center:  'text-align:center',
  left:    'text-align:left',
  right:   'text-align:right',
  justify: 'text-align:justify',
  mono:    'font-family:var(--font-mono)',
  serif:   'font-family:var(--font-serif)',
  sans:    'font-family:var(--font-sans)',
  vertical: 'writing-mode:vertical-lr' ,
  wrap:     'word-wrap:break-word',
  dots:     'overflow:hidden;text-overflow:ellipsis;white-space:nowrap;width:100%',
  cols:    { prop: 'columns:$',        def:"" },
  lh:      { prop: 'line-height:$',    def:"" },
  wg:      { prop: 'font-weight:$',    def:"" },
  font:    { prop: 'font-family:$',    def:"" },
  align:   { prop: 'vertical-align:$', def:"" },
  space:   { prop: 'white-space:$',    def:"" },
  shadow:  {
    one: 'text-shadow:3px 3px 2px #0000004d',
    prop: 'text-shadow:$',
    def: 'px',
  },
  stroke: {
    prop: '-webkit-text-stroke:$',
    def: 'px',
  },
  break: {
    prop: 'word-break:$',
    vals: { all: 'break-all', keep: 'keep-all', },
    def:""
  }
}