export function CreateStates(): {
    h: string;
    f: string;
    c: string;
    a: string;
    first: string;
    ft: string;
    last: string;
    lt: string;
    odd: string;
    od: string;
    even: string;
    ev: string;
    all: string;
    '*': string;
    every: string;
    '>': string;
    between: string;
    bt: string;
    after: string;
    aft: string;
    before: string;
    bef: string;
    dark: (selector: any) => string;
};
